### ISSUE TITLE
about noise2noist result

### ISSUE THREAD

**Issue by leeqiaogithub** [majedelhelou/SFM#2]
hi.I tried Official TensorFlow implementation of  N2N,and added SFM while training.But the result of n2n does not restore a clean image.do you know why?or what details you have to emphasize.

I added SFM after adding possion noise,and i have checked the result of the outputs of above operations.Any help would be great.

**Comment by sfm-sr-denoising** [comment]
Hi, can you please provide more details on how you trained your TensorFlow N2N model? From personal experience with N2N, it was not always easy to get it to converge and it sometimes crashed (with a loss of up to around 10dB relative to the best when it crashes on AWGN for example).
