### ISSUE TITLE
don't use SFM

### ISSUE THREAD

**Issue by sibangde** [majedelhelou/SFM#6]
in the SR directory, the code of using SFM is:
`# SFM
if (sfm > 0 and random.random() > 0.5):
        img_lr_masked, mask = random_drop(lr_img, mode=0)
if (lr_dataset != 'None'):
        lr_img = cv2.imresize(lr_img, (0,0), fx=1/scale, fy=1/scale)`
but the 'img_lr_masked' is not used later, why?

**Comment by majedelhelou** [comment]
This must have been a typo that occurred during our code cleanup phase, good catch. We pushed a new commit that fixes this.
